version: '3.8'

services:
  # Contenedor de PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: tfg_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: proyecto
      POSTGRES_USER: proyecto
      POSTGRES_PASSWORD: proyecto
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./Base_de_Datos/BDD.sql:/docker-entrypoint-initdb.d/01-init.sql:ro"
    ports:
      - "5432:5432"
    networks:
      - tfg_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U proyecto -d proyecto || pg_isready -h localhost -p 5432"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Contenedor de Apache + PHP
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tfg_web
    restart: unless-stopped
    ports:
      - "8080:80"  
    volumes:
      - ./:/var/www/html:cached
      - web_logs:/var/log/apache2
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Variables de conexión a la base de datos
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: proyecto
      DB_USER: proyecto
      DB_PASSWORD: proyecto
      # Variables PHP
      PHP_MEMORY_LIMIT: 256M
      PHP_UPLOAD_MAX_FILESIZE: 10M
      PHP_POST_MAX_SIZE: 10M
    networks:
      - tfg_network

volumes:
  postgres_data:
    driver: local
  web_logs:
    driver: local

networks:
  tfg_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16