version: '3.8'

services:
  # Contenedor de PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: tfg_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: tfg_notas
      POSTGRES_USER: tfg_user
      POSTGRES_PASSWORD: tfg_secure_password_2024
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Base de Datos/BDD.sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "5433:5432"
    networks:
      - tfg_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tfg_user -d tfg_notas"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Contenedor de Apache + PHP
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tfg_web
    restart: unless-stopped
    ports:
      - "8080:80"  
    volumes:
      - ./:/var/www/html:cached
      - web_logs:/var/log/apache2
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Variables de conexión a la base de datos
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: proyecto
      DB_USER: proyecto
      DB_PASSWORD: proyecto
      # Variables PHP
      PHP_MEMORY_LIMIT: 256M
      PHP_UPLOAD_MAX_FILESIZE: 10M
      PHP_POST_MAX_SIZE: 10M
    networks:
      - tfg_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  web_logs:
    driver: local

networks:
  tfg_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16